# coding: utf-8

"""
    Swagger HodDB

    This is a description of the HodDB API

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.body import Body


class TestBody(unittest.TestCase):
    """ Body unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody(self):
        """
        Test Body
        """
        model = swagger_client.models.body.Body()


if __name__ == '__main__':
    unittest.main()
