// Code generated by gocc; DO NOT EDIT.

package token

import (
	"fmt"
)

type Token struct {
	Type
	Lit []byte
	Pos
}

type Type int

const (
	INVALID Type = iota
	EOF
)

type Pos struct {
	Offset int
	Line   int
	Column int
}

func (p Pos) String() string {
	return fmt.Sprintf("Pos(offset=%d, line=%d, column=%d)", p.Offset, p.Line, p.Column)
}

type TokenMap struct {
	typeMap []string
	idMap   map[string]Type
}

func (m TokenMap) Id(tok Type) string {
	if int(tok) < len(m.typeMap) {
		return m.typeMap[tok]
	}
	return "unknown"
}

func (m TokenMap) Type(tok string) Type {
	if typ, exist := m.idMap[tok]; exist {
		return typ
	}
	return INVALID
}

func (m TokenMap) TokenString(tok *Token) string {
	//TODO: refactor to print pos & token string properly
	return fmt.Sprintf("%s(%d,%s)", m.Id(tok.Type), tok.Type, tok.Lit)
}

func (m TokenMap) StringType(typ Type) string {
	return fmt.Sprintf("%s(%d)", m.Id(typ), typ)
}

var TokMap = TokenMap{
	typeMap: []string{
		"INVALID",
		"$",
		";",
		"SELECT",
		"*",
		"INSERT",
		"{",
		"}",
		".",
		"COUNT",
		"string",
		"var",
		"FROM",
		"empty",
		"TO",
		"AT",
		"BEFORE",
		"AFTER",
		"WHERE",
		"uri",
		"quotedstring",
		"url",
		"|",
		"/",
		"a",
		"(",
		")",
		"?",
		"+",
		"UNION",
	},

	idMap: map[string]Type{
		"INVALID":      0,
		"$":            1,
		";":            2,
		"SELECT":       3,
		"*":            4,
		"INSERT":       5,
		"{":            6,
		"}":            7,
		".":            8,
		"COUNT":        9,
		"string":       10,
		"var":          11,
		"FROM":         12,
		"empty":        13,
		"TO":           14,
		"AT":           15,
		"BEFORE":       16,
		"AFTER":        17,
		"WHERE":        18,
		"uri":          19,
		"quotedstring": 20,
		"url":          21,
		"|":            22,
		"/":            23,
		"a":            24,
		"(":            25,
		")":            26,
		"?":            27,
		"+":            28,
		"UNION":        29,
	},
}
