# coding: utf-8

"""
    Swagger HodDB

    This is a description of the HodDB API

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InlineResponse200(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, rows=None, count=None, elapsed=None):
        """
        InlineResponse200 - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'rows': 'list[object]',
            'count': 'int',
            'elapsed': 'int'
        }

        self.attribute_map = {
            'rows': 'Rows',
            'count': 'Count',
            'elapsed': 'Elapsed'
        }

        self._rows = rows
        self._count = count
        self._elapsed = elapsed

    @property
    def rows(self):
        """
        Gets the rows of this InlineResponse200.
        Query results

        :return: The rows of this InlineResponse200.
        :rtype: list[object]
        """
        return self._rows

    @rows.setter
    def rows(self, rows):
        """
        Sets the rows of this InlineResponse200.
        Query results

        :param rows: The rows of this InlineResponse200.
        :type: list[object]
        """

        self._rows = rows

    @property
    def count(self):
        """
        Gets the count of this InlineResponse200.
        Number of rows returned

        :return: The count of this InlineResponse200.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """
        Sets the count of this InlineResponse200.
        Number of rows returned

        :param count: The count of this InlineResponse200.
        :type: int
        """

        self._count = count

    @property
    def elapsed(self):
        """
        Gets the elapsed of this InlineResponse200.
        Nanoseconds elapsed during evaluation

        :return: The elapsed of this InlineResponse200.
        :rtype: int
        """
        return self._elapsed

    @elapsed.setter
    def elapsed(self, elapsed):
        """
        Sets the elapsed of this InlineResponse200.
        Nanoseconds elapsed during evaluation

        :param elapsed: The elapsed of this InlineResponse200.
        :type: int
        """

        self._elapsed = elapsed

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InlineResponse200):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
