// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,      /* INVALID */
			nil,      /* $ */
			nil,      /* ; */
			shift(6), /* SELECT */
			nil,      /* * */
			shift(7), /* COUNT */
			nil,      /* string */
			nil,      /* var */
			nil,      /* FROM */
			nil,      /* WHERE */
			nil,      /* { */
			nil,      /* } */
			nil,      /* . */
			nil,      /* uri */
			nil,      /* quotedstring */
			nil,      /* url */
			nil,      /* | */
			nil,      /* / */
			nil,      /* a */
			nil,      /* ( */
			nil,      /* ) */
			nil,      /* ? */
			nil,      /* + */
			nil,      /* empty */
			nil,      /* UNION */
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          /* INVALID */
			accept(true), /* $ */
			nil,          /* ; */
			nil,          /* SELECT */
			nil,          /* * */
			nil,          /* COUNT */
			nil,          /* string */
			nil,          /* var */
			nil,          /* FROM */
			nil,          /* WHERE */
			nil,          /* { */
			nil,          /* } */
			nil,          /* . */
			nil,          /* uri */
			nil,          /* quotedstring */
			nil,          /* url */
			nil,          /* | */
			nil,          /* / */
			nil,          /* a */
			nil,          /* ( */
			nil,          /* ) */
			nil,          /* ? */
			nil,          /* + */
			nil,          /* empty */
			nil,          /* UNION */
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,      /* INVALID */
			nil,      /* $ */
			shift(8), /* ; */
			nil,      /* SELECT */
			nil,      /* * */
			nil,      /* COUNT */
			nil,      /* string */
			nil,      /* var */
			nil,      /* FROM */
			nil,      /* WHERE */
			nil,      /* { */
			nil,      /* } */
			nil,      /* . */
			nil,      /* uri */
			nil,      /* quotedstring */
			nil,      /* url */
			nil,      /* | */
			nil,      /* / */
			nil,      /* a */
			nil,      /* ( */
			nil,      /* ) */
			nil,      /* ? */
			nil,      /* + */
			nil,      /* empty */
			nil,      /* UNION */
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,      /* INVALID */
			nil,      /* $ */
			shift(9), /* ; */
			nil,      /* SELECT */
			nil,      /* * */
			nil,      /* COUNT */
			nil,      /* string */
			nil,      /* var */
			nil,      /* FROM */
			nil,      /* WHERE */
			nil,      /* { */
			nil,      /* } */
			nil,      /* . */
			nil,      /* uri */
			nil,      /* quotedstring */
			nil,      /* url */
			nil,      /* | */
			nil,      /* / */
			nil,      /* a */
			nil,      /* ( */
			nil,      /* ) */
			nil,      /* ? */
			nil,      /* + */
			nil,      /* empty */
			nil,      /* UNION */
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			nil,       /* var */
			shift(12), /* FROM */
			shift(13), /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* quotedstring */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			nil,       /* var */
			shift(12), /* FROM */
			shift(13), /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* quotedstring */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			shift(16), /* * */
			nil,       /* COUNT */
			nil,       /* string */
			shift(19), /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* quotedstring */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			shift(20), /* * */
			nil,       /* COUNT */
			nil,       /* string */
			shift(19), /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* quotedstring */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(1), /* $, reduce: QueryUnit */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* quotedstring */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(2), /* $, reduce: QueryUnit */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* quotedstring */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			nil,       /* var */
			nil,       /* FROM */
			shift(13), /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* quotedstring */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			reduce(4), /* ;, reduce: SelectQuery */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* quotedstring */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			shift(23), /* * */
			nil,       /* COUNT */
			shift(26), /* string */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* quotedstring */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			shift(27), /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* quotedstring */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			nil,       /* var */
			nil,       /* FROM */
			shift(13), /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* quotedstring */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			reduce(6), /* ;, reduce: CountQuery */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* quotedstring */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			nil,       /* var */
			reduce(7), /* FROM, reduce: SelectClause */
			reduce(7), /* WHERE, reduce: SelectClause */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* quotedstring */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			shift(19), /* var */
			reduce(8), /* FROM, reduce: SelectClause */
			reduce(8), /* WHERE, reduce: SelectClause */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* quotedstring */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(11), /* var, reduce: Varlist */
			reduce(11), /* FROM, reduce: Varlist */
			reduce(11), /* WHERE, reduce: Varlist */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(16), /* var, reduce: Var */
			reduce(16), /* FROM, reduce: Var */
			reduce(16), /* WHERE, reduce: Var */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			nil,       /* var */
			reduce(9), /* FROM, reduce: CountClause */
			reduce(9), /* WHERE, reduce: CountClause */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* quotedstring */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			shift(19),  /* var */
			reduce(10), /* FROM, reduce: CountClause */
			reduce(10), /* WHERE, reduce: CountClause */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			reduce(3), /* ;, reduce: SelectQuery */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* quotedstring */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			reduce(18), /* WHERE, reduce: DatasetClause */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			shift(26),  /* string */
			nil,        /* var */
			nil,        /* FROM */
			reduce(17), /* WHERE, reduce: DatasetClause */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			reduce(13), /* string, reduce: DBlist */
			nil,        /* var */
			nil,        /* FROM */
			reduce(13), /* WHERE, reduce: DBlist */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			reduce(15), /* string, reduce: String */
			nil,        /* var */
			nil,        /* FROM */
			reduce(15), /* WHERE, reduce: String */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			shift(32), /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			shift(33), /* { */
			nil,       /* } */
			nil,       /* . */
			shift(39), /* uri */
			shift(40), /* quotedstring */
			shift(41), /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			reduce(5), /* ;, reduce: CountQuery */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* quotedstring */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(12), /* var, reduce: Varlist */
			reduce(12), /* FROM, reduce: Varlist */
			reduce(12), /* WHERE, reduce: Varlist */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			reduce(14), /* string, reduce: DBlist */
			nil,        /* var */
			nil,        /* FROM */
			reduce(14), /* WHERE, reduce: DBlist */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(27), /* var, reduce: VarOrTerm */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(27), /* uri, reduce: VarOrTerm */
			nil,        /* quotedstring */
			reduce(27), /* url, reduce: VarOrTerm */
			nil,        /* | */
			nil,        /* / */
			reduce(27), /* a, reduce: VarOrTerm */
			reduce(27), /* (, reduce: VarOrTerm */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(16), /* var, reduce: Var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(16), /* uri, reduce: Var */
			nil,        /* quotedstring */
			reduce(16), /* url, reduce: Var */
			nil,        /* | */
			nil,        /* / */
			reduce(16), /* a, reduce: Var */
			reduce(16), /* (, reduce: Var */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			shift(32), /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			shift(45), /* { */
			nil,       /* } */
			nil,       /* . */
			shift(39), /* uri */
			shift(40), /* quotedstring */
			shift(41), /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			shift(33), /* { */
			shift(50), /* } */
			shift(51), /* . */
			nil,       /* uri */
			nil,       /* quotedstring */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S35
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			shift(33), /* { */
			shift(53), /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* quotedstring */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S36
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			reduce(24), /* {, reduce: TriplesBlock */
			reduce(24), /* }, reduce: TriplesBlock */
			reduce(24), /* ., reduce: TriplesBlock */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S37
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			shift(56), /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			shift(58), /* uri */
			nil,       /* quotedstring */
			shift(59), /* url */
			nil,       /* | */
			nil,       /* / */
			shift(63), /* a */
			shift(64), /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S38
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(28), /* var, reduce: VarOrTerm */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(28), /* uri, reduce: VarOrTerm */
			nil,        /* quotedstring */
			reduce(28), /* url, reduce: VarOrTerm */
			nil,        /* | */
			nil,        /* / */
			reduce(28), /* a, reduce: VarOrTerm */
			reduce(28), /* (, reduce: VarOrTerm */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S39
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(29), /* var, reduce: GraphTerm */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(29), /* uri, reduce: GraphTerm */
			nil,        /* quotedstring */
			reduce(29), /* url, reduce: GraphTerm */
			nil,        /* | */
			nil,        /* / */
			reduce(29), /* a, reduce: GraphTerm */
			reduce(29), /* (, reduce: GraphTerm */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S40
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(30), /* var, reduce: GraphTerm */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(30), /* uri, reduce: GraphTerm */
			nil,        /* quotedstring */
			reduce(30), /* url, reduce: GraphTerm */
			nil,        /* | */
			nil,        /* / */
			reduce(30), /* a, reduce: GraphTerm */
			reduce(30), /* (, reduce: GraphTerm */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S41
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(31), /* var, reduce: GraphTerm */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(31), /* uri, reduce: GraphTerm */
			nil,        /* quotedstring */
			reduce(31), /* url, reduce: GraphTerm */
			nil,        /* | */
			nil,        /* / */
			reduce(31), /* a, reduce: GraphTerm */
			reduce(31), /* (, reduce: GraphTerm */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S42
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			reduce(46), /* {, reduce: RestOfWhereList */
			reduce(46), /* }, reduce: RestOfWhereList */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S43
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(51), /* var, reduce: Joiner */
			nil,        /* FROM */
			nil,        /* WHERE */
			reduce(51), /* {, reduce: Joiner */
			reduce(51), /* }, reduce: Joiner */
			shift(65),  /* . */
			reduce(51), /* uri, reduce: Joiner */
			reduce(51), /* quotedstring, reduce: Joiner */
			reduce(51), /* url, reduce: Joiner */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			shift(67),  /* UNION */
		},
	},
	actionRow{ // S44
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(52), /* var, reduce: GraphPatternNotTriples */
			nil,        /* FROM */
			nil,        /* WHERE */
			reduce(52), /* {, reduce: GraphPatternNotTriples */
			reduce(52), /* }, reduce: GraphPatternNotTriples */
			reduce(52), /* ., reduce: GraphPatternNotTriples */
			reduce(52), /* uri, reduce: GraphPatternNotTriples */
			reduce(52), /* quotedstring, reduce: GraphPatternNotTriples */
			reduce(52), /* url, reduce: GraphPatternNotTriples */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			reduce(52), /* UNION, reduce: GraphPatternNotTriples */
		},
	},
	actionRow{ // S45
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			shift(32), /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			shift(45), /* { */
			nil,       /* } */
			nil,       /* . */
			shift(39), /* uri */
			shift(40), /* quotedstring */
			shift(41), /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S46
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			reduce(55), /* {, reduce: GroupGraphPatternSub */
			reduce(55), /* }, reduce: GroupGraphPatternSub */
			shift(69),  /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S47
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			shift(70), /* . */
			nil,       /* uri */
			nil,       /* quotedstring */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			shift(71), /* UNION */
		},
	},
	actionRow{ // S48
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			reduce(52), /* ., reduce: GraphPatternNotTriples */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			reduce(52), /* UNION, reduce: GraphPatternNotTriples */
		},
	},
	actionRow{ // S49
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			shift(45),  /* { */
			reduce(51), /* }, reduce: Joiner */
			shift(72),  /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S50
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			reduce(19), /* ;, reduce: WhereClause */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S51
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			shift(32), /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			shift(33), /* { */
			shift(75), /* } */
			nil,       /* . */
			shift(39), /* uri */
			shift(40), /* quotedstring */
			shift(41), /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S52
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			shift(33), /* { */
			shift(78), /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* quotedstring */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S53
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			reduce(23), /* ;, reduce: WhereClause */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S54
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			reduce(47), /* {, reduce: RestOfWhereList */
			reduce(47), /* }, reduce: RestOfWhereList */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S55
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(34), /* var, reduce: Path */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(34), /* uri, reduce: Path */
			reduce(34), /* quotedstring, reduce: Path */
			reduce(34), /* url, reduce: Path */
			reduce(34), /* |, reduce: Path */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S56
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(16), /* var, reduce: Var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(16), /* uri, reduce: Var */
			reduce(16), /* quotedstring, reduce: Var */
			reduce(16), /* url, reduce: Var */
			reduce(16), /* |, reduce: Var */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S57
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			shift(80), /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			shift(83), /* uri */
			shift(84), /* quotedstring */
			shift(85), /* url */
			shift(86), /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S58
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			reduce(39), /* *, reduce: PathPrimary */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(39), /* var, reduce: PathPrimary */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(39), /* uri, reduce: PathPrimary */
			reduce(39), /* quotedstring, reduce: PathPrimary */
			reduce(39), /* url, reduce: PathPrimary */
			reduce(39), /* |, reduce: PathPrimary */
			reduce(39), /* /, reduce: PathPrimary */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			reduce(39), /* ?, reduce: PathPrimary */
			reduce(39), /* +, reduce: PathPrimary */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S59
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			reduce(41), /* *, reduce: PathPrimary */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(41), /* var, reduce: PathPrimary */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(41), /* uri, reduce: PathPrimary */
			reduce(41), /* quotedstring, reduce: PathPrimary */
			reduce(41), /* url, reduce: PathPrimary */
			reduce(41), /* |, reduce: PathPrimary */
			reduce(41), /* /, reduce: PathPrimary */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			reduce(41), /* ?, reduce: PathPrimary */
			reduce(41), /* +, reduce: PathPrimary */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S60
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(32), /* var, reduce: Path */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(32), /* uri, reduce: Path */
			reduce(32), /* quotedstring, reduce: Path */
			reduce(32), /* url, reduce: Path */
			reduce(32), /* |, reduce: Path */
			shift(87),  /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S61
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(35), /* var, reduce: PathSequence */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(35), /* uri, reduce: PathSequence */
			reduce(35), /* quotedstring, reduce: PathSequence */
			reduce(35), /* url, reduce: PathSequence */
			reduce(35), /* |, reduce: PathSequence */
			reduce(35), /* /, reduce: PathSequence */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S62
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			shift(88),  /* * */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(38), /* var, reduce: PathElt */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(38), /* uri, reduce: PathElt */
			reduce(38), /* quotedstring, reduce: PathElt */
			reduce(38), /* url, reduce: PathElt */
			reduce(38), /* |, reduce: PathElt */
			reduce(38), /* /, reduce: PathElt */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			shift(90),  /* ? */
			shift(91),  /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S63
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			reduce(40), /* *, reduce: PathPrimary */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(40), /* var, reduce: PathPrimary */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(40), /* uri, reduce: PathPrimary */
			reduce(40), /* quotedstring, reduce: PathPrimary */
			reduce(40), /* url, reduce: PathPrimary */
			reduce(40), /* |, reduce: PathPrimary */
			reduce(40), /* /, reduce: PathPrimary */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			reduce(40), /* ?, reduce: PathPrimary */
			reduce(40), /* +, reduce: PathPrimary */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S64
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			shift(93),  /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			shift(95),  /* uri */
			nil,        /* quotedstring */
			shift(96),  /* url */
			nil,        /* | */
			nil,        /* / */
			shift(100), /* a */
			shift(101), /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S65
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(50), /* var, reduce: Joiner */
			nil,        /* FROM */
			nil,        /* WHERE */
			reduce(50), /* {, reduce: Joiner */
			reduce(50), /* }, reduce: Joiner */
			nil,        /* . */
			reduce(50), /* uri, reduce: Joiner */
			reduce(50), /* quotedstring, reduce: Joiner */
			reduce(50), /* url, reduce: Joiner */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S66
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			shift(32),  /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			reduce(49), /* {, reduce: RestOfWhere */
			reduce(49), /* }, reduce: RestOfWhere */
			nil,        /* . */
			shift(39),  /* uri */
			shift(40),  /* quotedstring */
			shift(41),  /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S67
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			shift(33), /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* quotedstring */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S68
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			shift(45),  /* { */
			reduce(51), /* }, reduce: Joiner */
			shift(72),  /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S69
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			shift(32), /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			shift(39), /* uri */
			shift(40), /* quotedstring */
			shift(41), /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S70
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			shift(32), /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			shift(39), /* uri */
			shift(40), /* quotedstring */
			shift(41), /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S71
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			shift(45), /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* quotedstring */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S72
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			reduce(50), /* }, reduce: Joiner */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S73
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			shift(107), /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			shift(71),  /* UNION */
		},
	},
	actionRow{ // S74
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			shift(108), /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S75
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			reduce(20), /* ;, reduce: WhereClause */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S76
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			shift(33),  /* { */
			shift(109), /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S77
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			reduce(25), /* {, reduce: TriplesBlock */
			reduce(25), /* }, reduce: TriplesBlock */
			reduce(25), /* ., reduce: TriplesBlock */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S78
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			reduce(21), /* ;, reduce: WhereClause */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S79
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			reduce(27), /* {, reduce: VarOrTerm */
			reduce(27), /* }, reduce: VarOrTerm */
			reduce(27), /* ., reduce: VarOrTerm */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S80
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			reduce(16), /* {, reduce: Var */
			reduce(16), /* }, reduce: Var */
			reduce(16), /* ., reduce: Var */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S81
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			reduce(26), /* {, reduce: Triple */
			reduce(26), /* }, reduce: Triple */
			reduce(26), /* ., reduce: Triple */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S82
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			reduce(28), /* {, reduce: VarOrTerm */
			reduce(28), /* }, reduce: VarOrTerm */
			reduce(28), /* ., reduce: VarOrTerm */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S83
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			reduce(29), /* {, reduce: GraphTerm */
			reduce(29), /* }, reduce: GraphTerm */
			reduce(29), /* ., reduce: GraphTerm */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S84
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			reduce(30), /* {, reduce: GraphTerm */
			reduce(30), /* }, reduce: GraphTerm */
			reduce(30), /* ., reduce: GraphTerm */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S85
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			reduce(31), /* {, reduce: GraphTerm */
			reduce(31), /* }, reduce: GraphTerm */
			reduce(31), /* ., reduce: GraphTerm */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S86
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			shift(58), /* uri */
			nil,       /* quotedstring */
			shift(59), /* url */
			nil,       /* | */
			nil,       /* / */
			shift(63), /* a */
			shift(64), /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S87
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			shift(58), /* uri */
			nil,       /* quotedstring */
			shift(59), /* url */
			nil,       /* | */
			nil,       /* / */
			shift(63), /* a */
			shift(64), /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S88
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(44), /* var, reduce: PathMod */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(44), /* uri, reduce: PathMod */
			reduce(44), /* quotedstring, reduce: PathMod */
			reduce(44), /* url, reduce: PathMod */
			reduce(44), /* |, reduce: PathMod */
			reduce(44), /* /, reduce: PathMod */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S89
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(37), /* var, reduce: PathElt */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(37), /* uri, reduce: PathElt */
			reduce(37), /* quotedstring, reduce: PathElt */
			reduce(37), /* url, reduce: PathElt */
			reduce(37), /* |, reduce: PathElt */
			reduce(37), /* /, reduce: PathElt */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S90
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(43), /* var, reduce: PathMod */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(43), /* uri, reduce: PathMod */
			reduce(43), /* quotedstring, reduce: PathMod */
			reduce(43), /* url, reduce: PathMod */
			reduce(43), /* |, reduce: PathMod */
			reduce(43), /* /, reduce: PathMod */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S91
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(45), /* var, reduce: PathMod */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(45), /* uri, reduce: PathMod */
			reduce(45), /* quotedstring, reduce: PathMod */
			reduce(45), /* url, reduce: PathMod */
			reduce(45), /* |, reduce: PathMod */
			reduce(45), /* /, reduce: PathMod */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S92
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			reduce(34), /* |, reduce: Path */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			reduce(34), /* ), reduce: Path */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S93
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			reduce(16), /* |, reduce: Var */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			reduce(16), /* ), reduce: Var */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S94
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			shift(112), /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			shift(113), /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S95
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			reduce(39), /* *, reduce: PathPrimary */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			reduce(39), /* |, reduce: PathPrimary */
			reduce(39), /* /, reduce: PathPrimary */
			nil,        /* a */
			nil,        /* ( */
			reduce(39), /* ), reduce: PathPrimary */
			reduce(39), /* ?, reduce: PathPrimary */
			reduce(39), /* +, reduce: PathPrimary */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S96
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			reduce(41), /* *, reduce: PathPrimary */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			reduce(41), /* |, reduce: PathPrimary */
			reduce(41), /* /, reduce: PathPrimary */
			nil,        /* a */
			nil,        /* ( */
			reduce(41), /* ), reduce: PathPrimary */
			reduce(41), /* ?, reduce: PathPrimary */
			reduce(41), /* +, reduce: PathPrimary */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S97
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			reduce(32), /* |, reduce: Path */
			shift(114), /* / */
			nil,        /* a */
			nil,        /* ( */
			reduce(32), /* ), reduce: Path */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S98
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			reduce(35), /* |, reduce: PathSequence */
			reduce(35), /* /, reduce: PathSequence */
			nil,        /* a */
			nil,        /* ( */
			reduce(35), /* ), reduce: PathSequence */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S99
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			shift(115), /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			reduce(38), /* |, reduce: PathElt */
			reduce(38), /* /, reduce: PathElt */
			nil,        /* a */
			nil,        /* ( */
			reduce(38), /* ), reduce: PathElt */
			shift(117), /* ? */
			shift(118), /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S100
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			reduce(40), /* *, reduce: PathPrimary */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			reduce(40), /* |, reduce: PathPrimary */
			reduce(40), /* /, reduce: PathPrimary */
			nil,        /* a */
			nil,        /* ( */
			reduce(40), /* ), reduce: PathPrimary */
			reduce(40), /* ?, reduce: PathPrimary */
			reduce(40), /* +, reduce: PathPrimary */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S101
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			shift(93),  /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			shift(95),  /* uri */
			nil,        /* quotedstring */
			shift(96),  /* url */
			nil,        /* | */
			nil,        /* / */
			shift(100), /* a */
			shift(101), /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S102
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			reduce(51), /* {, reduce: Joiner */
			reduce(51), /* }, reduce: Joiner */
			shift(120), /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S103
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(53), /* var, reduce: GraphPatternNotTriples */
			nil,        /* FROM */
			nil,        /* WHERE */
			reduce(53), /* {, reduce: GraphPatternNotTriples */
			reduce(53), /* }, reduce: GraphPatternNotTriples */
			reduce(53), /* ., reduce: GraphPatternNotTriples */
			reduce(53), /* uri, reduce: GraphPatternNotTriples */
			reduce(53), /* quotedstring, reduce: GraphPatternNotTriples */
			reduce(53), /* url, reduce: GraphPatternNotTriples */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			reduce(53), /* UNION, reduce: GraphPatternNotTriples */
		},
	},
	actionRow{ // S104
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			shift(122), /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S105
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			reduce(56), /* {, reduce: GroupGraphPatternSub */
			reduce(56), /* }, reduce: GroupGraphPatternSub */
			shift(69),  /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S106
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			reduce(53), /* ., reduce: GraphPatternNotTriples */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			reduce(53), /* UNION, reduce: GraphPatternNotTriples */
		},
	},
	actionRow{ // S107
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ; */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* COUNT */
			nil,       /* string */
			shift(32), /* var */
			nil,       /* FROM */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			shift(39), /* uri */
			shift(40), /* quotedstring */
			shift(41), /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S108
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(54), /* var, reduce: GroupGraphPattern */
			nil,        /* FROM */
			nil,        /* WHERE */
			reduce(54), /* {, reduce: GroupGraphPattern */
			reduce(54), /* }, reduce: GroupGraphPattern */
			reduce(54), /* ., reduce: GroupGraphPattern */
			reduce(54), /* uri, reduce: GroupGraphPattern */
			reduce(54), /* quotedstring, reduce: GroupGraphPattern */
			reduce(54), /* url, reduce: GroupGraphPattern */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			reduce(54), /* UNION, reduce: GroupGraphPattern */
		},
	},
	actionRow{ // S109
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			reduce(22), /* ;, reduce: WhereClause */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S110
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(33), /* var, reduce: Path */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(33), /* uri, reduce: Path */
			reduce(33), /* quotedstring, reduce: Path */
			reduce(33), /* url, reduce: Path */
			reduce(33), /* |, reduce: Path */
			shift(87),  /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S111
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(36), /* var, reduce: PathSequence */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(36), /* uri, reduce: PathSequence */
			reduce(36), /* quotedstring, reduce: PathSequence */
			reduce(36), /* url, reduce: PathSequence */
			reduce(36), /* |, reduce: PathSequence */
			reduce(36), /* /, reduce: PathSequence */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S112
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			shift(95),  /* uri */
			nil,        /* quotedstring */
			shift(96),  /* url */
			nil,        /* | */
			nil,        /* / */
			shift(100), /* a */
			shift(101), /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S113
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			reduce(42), /* *, reduce: PathPrimary */
			nil,        /* COUNT */
			nil,        /* string */
			reduce(42), /* var, reduce: PathPrimary */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(42), /* uri, reduce: PathPrimary */
			reduce(42), /* quotedstring, reduce: PathPrimary */
			reduce(42), /* url, reduce: PathPrimary */
			reduce(42), /* |, reduce: PathPrimary */
			reduce(42), /* /, reduce: PathPrimary */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			reduce(42), /* ?, reduce: PathPrimary */
			reduce(42), /* +, reduce: PathPrimary */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S114
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			shift(95),  /* uri */
			nil,        /* quotedstring */
			shift(96),  /* url */
			nil,        /* | */
			nil,        /* / */
			shift(100), /* a */
			shift(101), /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S115
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			reduce(44), /* |, reduce: PathMod */
			reduce(44), /* /, reduce: PathMod */
			nil,        /* a */
			nil,        /* ( */
			reduce(44), /* ), reduce: PathMod */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S116
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			reduce(37), /* |, reduce: PathElt */
			reduce(37), /* /, reduce: PathElt */
			nil,        /* a */
			nil,        /* ( */
			reduce(37), /* ), reduce: PathElt */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S117
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			reduce(43), /* |, reduce: PathMod */
			reduce(43), /* /, reduce: PathMod */
			nil,        /* a */
			nil,        /* ( */
			reduce(43), /* ), reduce: PathMod */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S118
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			reduce(45), /* |, reduce: PathMod */
			reduce(45), /* /, reduce: PathMod */
			nil,        /* a */
			nil,        /* ( */
			reduce(45), /* ), reduce: PathMod */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S119
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			shift(112), /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			shift(126), /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S120
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			shift(32),  /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			reduce(50), /* {, reduce: Joiner */
			reduce(50), /* }, reduce: Joiner */
			nil,        /* . */
			shift(39),  /* uri */
			shift(40),  /* quotedstring */
			shift(41),  /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S121
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			reduce(48), /* {, reduce: RestOfWhere */
			reduce(48), /* }, reduce: RestOfWhere */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S122
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			reduce(54), /* ., reduce: GroupGraphPattern */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			reduce(54), /* UNION, reduce: GroupGraphPattern */
		},
	},
	actionRow{ // S123
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			reduce(57), /* {, reduce: GroupGraphPatternSub */
			reduce(57), /* }, reduce: GroupGraphPatternSub */
			shift(69),  /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S124
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			reduce(33), /* |, reduce: Path */
			shift(114), /* / */
			nil,        /* a */
			nil,        /* ( */
			reduce(33), /* ), reduce: Path */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S125
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			reduce(36), /* |, reduce: PathSequence */
			reduce(36), /* /, reduce: PathSequence */
			nil,        /* a */
			nil,        /* ( */
			reduce(36), /* ), reduce: PathSequence */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S126
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ; */
			nil,        /* SELECT */
			reduce(42), /* *, reduce: PathPrimary */
			nil,        /* COUNT */
			nil,        /* string */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* quotedstring */
			nil,        /* url */
			reduce(42), /* |, reduce: PathPrimary */
			reduce(42), /* /, reduce: PathPrimary */
			nil,        /* a */
			nil,        /* ( */
			reduce(42), /* ), reduce: PathPrimary */
			reduce(42), /* ?, reduce: PathPrimary */
			reduce(42), /* +, reduce: PathPrimary */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
}
