// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,      /* INVALID */
			nil,      /* $ */
			shift(4), /* SELECT */
			nil,      /* * */
			nil,      /* var */
			nil,      /* FROM */
			nil,      /* string */
			nil,      /* WHERE */
			nil,      /* { */
			nil,      /* } */
			nil,      /* . */
			nil,      /* uri */
			nil,      /* url */
			nil,      /* | */
			nil,      /* / */
			nil,      /* a */
			nil,      /* ( */
			nil,      /* ) */
			nil,      /* ? */
			nil,      /* + */
			nil,      /* empty */
			nil,      /* UNION */
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          /* INVALID */
			accept(true), /* $ */
			nil,          /* SELECT */
			nil,          /* * */
			nil,          /* var */
			nil,          /* FROM */
			nil,          /* string */
			nil,          /* WHERE */
			nil,          /* { */
			nil,          /* } */
			nil,          /* . */
			nil,          /* uri */
			nil,          /* url */
			nil,          /* | */
			nil,          /* / */
			nil,          /* a */
			nil,          /* ( */
			nil,          /* ) */
			nil,          /* ? */
			nil,          /* + */
			nil,          /* empty */
			nil,          /* UNION */
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(1), /* $, reduce: QueryUnit */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* string */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,      /* INVALID */
			nil,      /* $ */
			nil,      /* SELECT */
			nil,      /* * */
			nil,      /* var */
			shift(7), /* FROM */
			nil,      /* string */
			shift(8), /* WHERE */
			nil,      /* { */
			nil,      /* } */
			nil,      /* . */
			nil,      /* uri */
			nil,      /* url */
			nil,      /* | */
			nil,      /* / */
			nil,      /* a */
			nil,      /* ( */
			nil,      /* ) */
			nil,      /* ? */
			nil,      /* + */
			nil,      /* empty */
			nil,      /* UNION */
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			shift(9),  /* * */
			shift(12), /* var */
			nil,       /* FROM */
			nil,       /* string */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,      /* INVALID */
			nil,      /* $ */
			nil,      /* SELECT */
			nil,      /* * */
			nil,      /* var */
			nil,      /* FROM */
			nil,      /* string */
			shift(8), /* WHERE */
			nil,      /* { */
			nil,      /* } */
			nil,      /* . */
			nil,      /* uri */
			nil,      /* url */
			nil,      /* | */
			nil,      /* / */
			nil,      /* a */
			nil,      /* ( */
			nil,      /* ) */
			nil,      /* ? */
			nil,      /* + */
			nil,      /* empty */
			nil,      /* UNION */
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(3), /* $, reduce: SelectQuery */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* string */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* var */
			nil,       /* FROM */
			shift(14), /* string */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* string */
			nil,       /* WHERE */
			shift(15), /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* var */
			reduce(4), /* FROM, reduce: SelectClause */
			nil,       /* string */
			reduce(4), /* WHERE, reduce: SelectClause */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			shift(12), /* var */
			reduce(5), /* FROM, reduce: SelectClause */
			nil,       /* string */
			reduce(5), /* WHERE, reduce: SelectClause */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			reduce(6), /* var, reduce: Varlist */
			reduce(6), /* FROM, reduce: Varlist */
			nil,       /* string */
			reduce(6), /* WHERE, reduce: Varlist */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			reduce(8), /* var, reduce: Var */
			reduce(8), /* FROM, reduce: Var */
			nil,       /* string */
			reduce(8), /* WHERE, reduce: Var */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(2), /* $, reduce: SelectQuery */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* string */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* string */
			reduce(9), /* WHERE, reduce: DatasetClause */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			shift(18), /* var */
			nil,       /* FROM */
			shift(19), /* string */
			nil,       /* WHERE */
			shift(20), /* { */
			nil,       /* } */
			nil,       /* . */
			shift(26), /* uri */
			shift(27), /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			reduce(7), /* var, reduce: Varlist */
			reduce(7), /* FROM, reduce: Varlist */
			nil,       /* string */
			reduce(7), /* WHERE, reduce: Varlist */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			reduce(16), /* var, reduce: VarOrTerm */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(16), /* uri, reduce: VarOrTerm */
			reduce(16), /* url, reduce: VarOrTerm */
			nil,        /* | */
			nil,        /* / */
			reduce(16), /* a, reduce: VarOrTerm */
			reduce(16), /* (, reduce: VarOrTerm */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			reduce(8), /* var, reduce: Var */
			nil,       /* FROM */
			nil,       /* string */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			reduce(8), /* uri, reduce: Var */
			reduce(8), /* url, reduce: Var */
			nil,       /* | */
			nil,       /* / */
			reduce(8), /* a, reduce: Var */
			reduce(8), /* (, reduce: Var */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			reduce(19), /* var, reduce: GraphTerm */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(19), /* uri, reduce: GraphTerm */
			reduce(19), /* url, reduce: GraphTerm */
			nil,        /* | */
			nil,        /* / */
			reduce(19), /* a, reduce: GraphTerm */
			reduce(19), /* (, reduce: GraphTerm */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			shift(18), /* var */
			nil,       /* FROM */
			shift(19), /* string */
			nil,       /* WHERE */
			shift(31), /* { */
			nil,       /* } */
			nil,       /* . */
			shift(26), /* uri */
			shift(27), /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* string */
			nil,       /* WHERE */
			shift(20), /* { */
			shift(36), /* } */
			shift(38), /* . */
			nil,       /* uri */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* string */
			nil,       /* WHERE */
			shift(20), /* { */
			shift(39), /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			reduce(13), /* {, reduce: TriplesBlock */
			reduce(13), /* }, reduce: TriplesBlock */
			reduce(13), /* ., reduce: TriplesBlock */
			nil,        /* uri */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			shift(42), /* var */
			nil,       /* FROM */
			nil,       /* string */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			shift(44), /* uri */
			shift(45), /* url */
			nil,       /* | */
			nil,       /* / */
			shift(49), /* a */
			shift(50), /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			reduce(17), /* var, reduce: VarOrTerm */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(17), /* uri, reduce: VarOrTerm */
			reduce(17), /* url, reduce: VarOrTerm */
			nil,        /* | */
			nil,        /* / */
			reduce(17), /* a, reduce: VarOrTerm */
			reduce(17), /* (, reduce: VarOrTerm */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			reduce(18), /* var, reduce: GraphTerm */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(18), /* uri, reduce: GraphTerm */
			reduce(18), /* url, reduce: GraphTerm */
			nil,        /* | */
			nil,        /* / */
			reduce(18), /* a, reduce: GraphTerm */
			reduce(18), /* (, reduce: GraphTerm */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			reduce(20), /* var, reduce: GraphTerm */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(20), /* uri, reduce: GraphTerm */
			reduce(20), /* url, reduce: GraphTerm */
			nil,        /* | */
			nil,        /* / */
			reduce(20), /* a, reduce: GraphTerm */
			reduce(20), /* (, reduce: GraphTerm */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			reduce(35), /* {, reduce: RestOfWhereList */
			reduce(35), /* }, reduce: RestOfWhereList */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			reduce(40), /* var, reduce: Joiner */
			nil,        /* FROM */
			reduce(40), /* string, reduce: Joiner */
			nil,        /* WHERE */
			reduce(38), /* {, reduce: RestOfWhere */
			reduce(38), /* }, reduce: RestOfWhere */
			shift(51),  /* . */
			reduce(40), /* uri, reduce: Joiner */
			reduce(40), /* url, reduce: Joiner */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			shift(53),  /* UNION */
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			reduce(41), /* var, reduce: GraphPatternNotTriples */
			nil,        /* FROM */
			reduce(41), /* string, reduce: GraphPatternNotTriples */
			nil,        /* WHERE */
			reduce(41), /* {, reduce: GraphPatternNotTriples */
			reduce(41), /* }, reduce: GraphPatternNotTriples */
			reduce(41), /* ., reduce: GraphPatternNotTriples */
			reduce(41), /* uri, reduce: GraphPatternNotTriples */
			reduce(41), /* url, reduce: GraphPatternNotTriples */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			reduce(41), /* UNION, reduce: GraphPatternNotTriples */
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			shift(18), /* var */
			nil,       /* FROM */
			shift(19), /* string */
			nil,       /* WHERE */
			shift(31), /* { */
			nil,       /* } */
			nil,       /* . */
			shift(26), /* uri */
			shift(27), /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			reduce(44), /* {, reduce: GroupGraphPatternSub */
			reduce(44), /* }, reduce: GroupGraphPatternSub */
			shift(38),  /* . */
			nil,        /* uri */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* string */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			shift(55), /* . */
			nil,       /* uri */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			shift(56), /* UNION */
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			reduce(41), /* ., reduce: GraphPatternNotTriples */
			nil,        /* uri */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			reduce(41), /* UNION, reduce: GraphPatternNotTriples */
		},
	},
	actionRow{ // S35
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* string */
			nil,       /* WHERE */
			shift(31), /* { */
			shift(57), /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S36
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(10), /* $, reduce: WhereClause */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S37
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* string */
			nil,       /* WHERE */
			shift(20), /* { */
			shift(59), /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S38
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			shift(18), /* var */
			nil,       /* FROM */
			shift(19), /* string */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			shift(26), /* uri */
			shift(27), /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S39
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(12), /* $, reduce: WhereClause */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S40
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			reduce(36), /* {, reduce: RestOfWhereList */
			reduce(36), /* }, reduce: RestOfWhereList */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S41
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			reduce(23), /* var, reduce: Path */
			nil,        /* FROM */
			reduce(23), /* string, reduce: Path */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(23), /* uri, reduce: Path */
			reduce(23), /* url, reduce: Path */
			reduce(23), /* |, reduce: Path */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S42
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			reduce(8), /* var, reduce: Var */
			nil,       /* FROM */
			reduce(8), /* string, reduce: Var */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			reduce(8), /* uri, reduce: Var */
			reduce(8), /* url, reduce: Var */
			reduce(8), /* |, reduce: Var */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S43
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			shift(62), /* var */
			nil,       /* FROM */
			shift(63), /* string */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			shift(66), /* uri */
			shift(67), /* url */
			shift(68), /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S44
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			reduce(28), /* *, reduce: PathPrimary */
			reduce(28), /* var, reduce: PathPrimary */
			nil,        /* FROM */
			reduce(28), /* string, reduce: PathPrimary */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(28), /* uri, reduce: PathPrimary */
			reduce(28), /* url, reduce: PathPrimary */
			reduce(28), /* |, reduce: PathPrimary */
			reduce(28), /* /, reduce: PathPrimary */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			reduce(28), /* ?, reduce: PathPrimary */
			reduce(28), /* +, reduce: PathPrimary */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S45
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			reduce(30), /* *, reduce: PathPrimary */
			reduce(30), /* var, reduce: PathPrimary */
			nil,        /* FROM */
			reduce(30), /* string, reduce: PathPrimary */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(30), /* uri, reduce: PathPrimary */
			reduce(30), /* url, reduce: PathPrimary */
			reduce(30), /* |, reduce: PathPrimary */
			reduce(30), /* /, reduce: PathPrimary */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			reduce(30), /* ?, reduce: PathPrimary */
			reduce(30), /* +, reduce: PathPrimary */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S46
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			reduce(21), /* var, reduce: Path */
			nil,        /* FROM */
			reduce(21), /* string, reduce: Path */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(21), /* uri, reduce: Path */
			reduce(21), /* url, reduce: Path */
			reduce(21), /* |, reduce: Path */
			shift(69),  /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S47
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			reduce(24), /* var, reduce: PathSequence */
			nil,        /* FROM */
			reduce(24), /* string, reduce: PathSequence */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(24), /* uri, reduce: PathSequence */
			reduce(24), /* url, reduce: PathSequence */
			reduce(24), /* |, reduce: PathSequence */
			reduce(24), /* /, reduce: PathSequence */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S48
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			shift(70),  /* * */
			reduce(27), /* var, reduce: PathElt */
			nil,        /* FROM */
			reduce(27), /* string, reduce: PathElt */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(27), /* uri, reduce: PathElt */
			reduce(27), /* url, reduce: PathElt */
			reduce(27), /* |, reduce: PathElt */
			reduce(27), /* /, reduce: PathElt */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			shift(72),  /* ? */
			shift(73),  /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S49
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			reduce(29), /* *, reduce: PathPrimary */
			reduce(29), /* var, reduce: PathPrimary */
			nil,        /* FROM */
			reduce(29), /* string, reduce: PathPrimary */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(29), /* uri, reduce: PathPrimary */
			reduce(29), /* url, reduce: PathPrimary */
			reduce(29), /* |, reduce: PathPrimary */
			reduce(29), /* /, reduce: PathPrimary */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			reduce(29), /* ?, reduce: PathPrimary */
			reduce(29), /* +, reduce: PathPrimary */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S50
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			shift(75), /* var */
			nil,       /* FROM */
			nil,       /* string */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			shift(77), /* uri */
			shift(78), /* url */
			nil,       /* | */
			nil,       /* / */
			shift(82), /* a */
			shift(83), /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S51
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			reduce(39), /* var, reduce: Joiner */
			nil,        /* FROM */
			reduce(39), /* string, reduce: Joiner */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(39), /* uri, reduce: Joiner */
			reduce(39), /* url, reduce: Joiner */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S52
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			shift(18), /* var */
			nil,       /* FROM */
			shift(19), /* string */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			shift(26), /* uri */
			shift(27), /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S53
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* string */
			nil,       /* WHERE */
			shift(20), /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S54
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* string */
			nil,       /* WHERE */
			shift(31), /* { */
			shift(86), /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S55
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			shift(18), /* var */
			nil,       /* FROM */
			shift(19), /* string */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			shift(26), /* uri */
			shift(27), /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S56
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* string */
			nil,       /* WHERE */
			shift(31), /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S57
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			reduce(43), /* var, reduce: GroupGraphPattern */
			nil,        /* FROM */
			reduce(43), /* string, reduce: GroupGraphPattern */
			nil,        /* WHERE */
			reduce(43), /* {, reduce: GroupGraphPattern */
			reduce(43), /* }, reduce: GroupGraphPattern */
			reduce(43), /* ., reduce: GroupGraphPattern */
			reduce(43), /* uri, reduce: GroupGraphPattern */
			reduce(43), /* url, reduce: GroupGraphPattern */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			reduce(43), /* UNION, reduce: GroupGraphPattern */
		},
	},
	actionRow{ // S58
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* string */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			shift(89), /* . */
			nil,       /* uri */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			shift(56), /* UNION */
		},
	},
	actionRow{ // S59
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(11), /* $, reduce: WhereClause */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S60
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			reduce(14), /* {, reduce: TriplesBlock */
			reduce(14), /* }, reduce: TriplesBlock */
			reduce(14), /* ., reduce: TriplesBlock */
			nil,        /* uri */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S61
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			reduce(16), /* {, reduce: VarOrTerm */
			reduce(16), /* }, reduce: VarOrTerm */
			reduce(16), /* ., reduce: VarOrTerm */
			nil,        /* uri */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S62
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* string */
			nil,       /* WHERE */
			reduce(8), /* {, reduce: Var */
			reduce(8), /* }, reduce: Var */
			reduce(8), /* ., reduce: Var */
			nil,       /* uri */
			nil,       /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S63
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			reduce(19), /* {, reduce: GraphTerm */
			reduce(19), /* }, reduce: GraphTerm */
			reduce(19), /* ., reduce: GraphTerm */
			nil,        /* uri */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S64
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			reduce(15), /* {, reduce: Triple */
			reduce(15), /* }, reduce: Triple */
			reduce(15), /* ., reduce: Triple */
			nil,        /* uri */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S65
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			reduce(17), /* {, reduce: VarOrTerm */
			reduce(17), /* }, reduce: VarOrTerm */
			reduce(17), /* ., reduce: VarOrTerm */
			nil,        /* uri */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S66
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			reduce(18), /* {, reduce: GraphTerm */
			reduce(18), /* }, reduce: GraphTerm */
			reduce(18), /* ., reduce: GraphTerm */
			nil,        /* uri */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S67
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			reduce(20), /* {, reduce: GraphTerm */
			reduce(20), /* }, reduce: GraphTerm */
			reduce(20), /* ., reduce: GraphTerm */
			nil,        /* uri */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S68
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* string */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			shift(44), /* uri */
			shift(45), /* url */
			nil,       /* | */
			nil,       /* / */
			shift(49), /* a */
			shift(50), /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S69
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* string */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			shift(44), /* uri */
			shift(45), /* url */
			nil,       /* | */
			nil,       /* / */
			shift(49), /* a */
			shift(50), /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S70
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			reduce(33), /* var, reduce: PathMod */
			nil,        /* FROM */
			reduce(33), /* string, reduce: PathMod */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(33), /* uri, reduce: PathMod */
			reduce(33), /* url, reduce: PathMod */
			reduce(33), /* |, reduce: PathMod */
			reduce(33), /* /, reduce: PathMod */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S71
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			reduce(26), /* var, reduce: PathElt */
			nil,        /* FROM */
			reduce(26), /* string, reduce: PathElt */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(26), /* uri, reduce: PathElt */
			reduce(26), /* url, reduce: PathElt */
			reduce(26), /* |, reduce: PathElt */
			reduce(26), /* /, reduce: PathElt */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S72
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			reduce(32), /* var, reduce: PathMod */
			nil,        /* FROM */
			reduce(32), /* string, reduce: PathMod */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(32), /* uri, reduce: PathMod */
			reduce(32), /* url, reduce: PathMod */
			reduce(32), /* |, reduce: PathMod */
			reduce(32), /* /, reduce: PathMod */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S73
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			reduce(34), /* var, reduce: PathMod */
			nil,        /* FROM */
			reduce(34), /* string, reduce: PathMod */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(34), /* uri, reduce: PathMod */
			reduce(34), /* url, reduce: PathMod */
			reduce(34), /* |, reduce: PathMod */
			reduce(34), /* /, reduce: PathMod */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S74
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* url */
			reduce(23), /* |, reduce: Path */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			reduce(23), /* ), reduce: Path */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S75
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* string */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* url */
			reduce(8), /* |, reduce: Var */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			reduce(8), /* ), reduce: Var */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S76
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* string */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			nil,       /* uri */
			nil,       /* url */
			shift(92), /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			shift(93), /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S77
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			reduce(28), /* *, reduce: PathPrimary */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* url */
			reduce(28), /* |, reduce: PathPrimary */
			reduce(28), /* /, reduce: PathPrimary */
			nil,        /* a */
			nil,        /* ( */
			reduce(28), /* ), reduce: PathPrimary */
			reduce(28), /* ?, reduce: PathPrimary */
			reduce(28), /* +, reduce: PathPrimary */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S78
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			reduce(30), /* *, reduce: PathPrimary */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* url */
			reduce(30), /* |, reduce: PathPrimary */
			reduce(30), /* /, reduce: PathPrimary */
			nil,        /* a */
			nil,        /* ( */
			reduce(30), /* ), reduce: PathPrimary */
			reduce(30), /* ?, reduce: PathPrimary */
			reduce(30), /* +, reduce: PathPrimary */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S79
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* url */
			reduce(21), /* |, reduce: Path */
			shift(94),  /* / */
			nil,        /* a */
			nil,        /* ( */
			reduce(21), /* ), reduce: Path */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S80
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* url */
			reduce(24), /* |, reduce: PathSequence */
			reduce(24), /* /, reduce: PathSequence */
			nil,        /* a */
			nil,        /* ( */
			reduce(24), /* ), reduce: PathSequence */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S81
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			shift(95),  /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* url */
			reduce(27), /* |, reduce: PathElt */
			reduce(27), /* /, reduce: PathElt */
			nil,        /* a */
			nil,        /* ( */
			reduce(27), /* ), reduce: PathElt */
			shift(97),  /* ? */
			shift(98),  /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S82
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			reduce(29), /* *, reduce: PathPrimary */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* url */
			reduce(29), /* |, reduce: PathPrimary */
			reduce(29), /* /, reduce: PathPrimary */
			nil,        /* a */
			nil,        /* ( */
			reduce(29), /* ), reduce: PathPrimary */
			reduce(29), /* ?, reduce: PathPrimary */
			reduce(29), /* +, reduce: PathPrimary */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S83
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			shift(75), /* var */
			nil,       /* FROM */
			nil,       /* string */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			shift(77), /* uri */
			shift(78), /* url */
			nil,       /* | */
			nil,       /* / */
			shift(82), /* a */
			shift(83), /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S84
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			reduce(37), /* {, reduce: RestOfWhere */
			reduce(37), /* }, reduce: RestOfWhere */
			shift(38),  /* . */
			nil,        /* uri */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S85
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			reduce(42), /* var, reduce: GraphPatternNotTriples */
			nil,        /* FROM */
			reduce(42), /* string, reduce: GraphPatternNotTriples */
			nil,        /* WHERE */
			reduce(42), /* {, reduce: GraphPatternNotTriples */
			reduce(42), /* }, reduce: GraphPatternNotTriples */
			reduce(42), /* ., reduce: GraphPatternNotTriples */
			reduce(42), /* uri, reduce: GraphPatternNotTriples */
			reduce(42), /* url, reduce: GraphPatternNotTriples */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			reduce(42), /* UNION, reduce: GraphPatternNotTriples */
		},
	},
	actionRow{ // S86
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			reduce(43), /* ., reduce: GroupGraphPattern */
			nil,        /* uri */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			reduce(43), /* UNION, reduce: GroupGraphPattern */
		},
	},
	actionRow{ // S87
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			reduce(45), /* {, reduce: GroupGraphPatternSub */
			reduce(45), /* }, reduce: GroupGraphPatternSub */
			shift(38),  /* . */
			nil,        /* uri */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S88
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			reduce(42), /* ., reduce: GraphPatternNotTriples */
			nil,        /* uri */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			reduce(42), /* UNION, reduce: GraphPatternNotTriples */
		},
	},
	actionRow{ // S89
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			shift(18), /* var */
			nil,       /* FROM */
			shift(19), /* string */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			shift(26), /* uri */
			shift(27), /* url */
			nil,       /* | */
			nil,       /* / */
			nil,       /* a */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S90
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			reduce(22), /* var, reduce: Path */
			nil,        /* FROM */
			reduce(22), /* string, reduce: Path */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(22), /* uri, reduce: Path */
			reduce(22), /* url, reduce: Path */
			reduce(22), /* |, reduce: Path */
			shift(69),  /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S91
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			reduce(25), /* var, reduce: PathSequence */
			nil,        /* FROM */
			reduce(25), /* string, reduce: PathSequence */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(25), /* uri, reduce: PathSequence */
			reduce(25), /* url, reduce: PathSequence */
			reduce(25), /* |, reduce: PathSequence */
			reduce(25), /* /, reduce: PathSequence */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S92
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* string */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			shift(77), /* uri */
			shift(78), /* url */
			nil,       /* | */
			nil,       /* / */
			shift(82), /* a */
			shift(83), /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S93
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			reduce(31), /* *, reduce: PathPrimary */
			reduce(31), /* var, reduce: PathPrimary */
			nil,        /* FROM */
			reduce(31), /* string, reduce: PathPrimary */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			reduce(31), /* uri, reduce: PathPrimary */
			reduce(31), /* url, reduce: PathPrimary */
			reduce(31), /* |, reduce: PathPrimary */
			reduce(31), /* /, reduce: PathPrimary */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			reduce(31), /* ?, reduce: PathPrimary */
			reduce(31), /* +, reduce: PathPrimary */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S94
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* SELECT */
			nil,       /* * */
			nil,       /* var */
			nil,       /* FROM */
			nil,       /* string */
			nil,       /* WHERE */
			nil,       /* { */
			nil,       /* } */
			nil,       /* . */
			shift(77), /* uri */
			shift(78), /* url */
			nil,       /* | */
			nil,       /* / */
			shift(82), /* a */
			shift(83), /* ( */
			nil,       /* ) */
			nil,       /* ? */
			nil,       /* + */
			nil,       /* empty */
			nil,       /* UNION */
		},
	},
	actionRow{ // S95
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* url */
			reduce(33), /* |, reduce: PathMod */
			reduce(33), /* /, reduce: PathMod */
			nil,        /* a */
			nil,        /* ( */
			reduce(33), /* ), reduce: PathMod */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S96
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* url */
			reduce(26), /* |, reduce: PathElt */
			reduce(26), /* /, reduce: PathElt */
			nil,        /* a */
			nil,        /* ( */
			reduce(26), /* ), reduce: PathElt */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S97
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* url */
			reduce(32), /* |, reduce: PathMod */
			reduce(32), /* /, reduce: PathMod */
			nil,        /* a */
			nil,        /* ( */
			reduce(32), /* ), reduce: PathMod */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S98
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* url */
			reduce(34), /* |, reduce: PathMod */
			reduce(34), /* /, reduce: PathMod */
			nil,        /* a */
			nil,        /* ( */
			reduce(34), /* ), reduce: PathMod */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S99
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* url */
			shift(92),  /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			shift(103), /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S100
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			reduce(46), /* {, reduce: GroupGraphPatternSub */
			reduce(46), /* }, reduce: GroupGraphPatternSub */
			shift(38),  /* . */
			nil,        /* uri */
			nil,        /* url */
			nil,        /* | */
			nil,        /* / */
			nil,        /* a */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S101
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* url */
			reduce(22), /* |, reduce: Path */
			shift(94),  /* / */
			nil,        /* a */
			nil,        /* ( */
			reduce(22), /* ), reduce: Path */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S102
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			nil,        /* * */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* url */
			reduce(25), /* |, reduce: PathSequence */
			reduce(25), /* /, reduce: PathSequence */
			nil,        /* a */
			nil,        /* ( */
			reduce(25), /* ), reduce: PathSequence */
			nil,        /* ? */
			nil,        /* + */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
	actionRow{ // S103
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* SELECT */
			reduce(31), /* *, reduce: PathPrimary */
			nil,        /* var */
			nil,        /* FROM */
			nil,        /* string */
			nil,        /* WHERE */
			nil,        /* { */
			nil,        /* } */
			nil,        /* . */
			nil,        /* uri */
			nil,        /* url */
			reduce(31), /* |, reduce: PathPrimary */
			reduce(31), /* /, reduce: PathPrimary */
			nil,        /* a */
			nil,        /* ( */
			reduce(31), /* ), reduce: PathPrimary */
			reduce(31), /* ?, reduce: PathPrimary */
			reduce(31), /* +, reduce: PathPrimary */
			nil,        /* empty */
			nil,        /* UNION */
		},
	},
}
