// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"io/ioutil"
	"unicode/utf8"

	"github.com/gtfierro/hod/lang/token"
)

const (
	NoState    = -1
	NumStates  = 62
	NumSymbols = 71
)

type Lexer struct {
	src    []byte
	pos    int
	line   int
	column int
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:    src,
		pos:    0,
		line:   1,
		column: 1,
	}
	return lexer
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := ioutil.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	return NewLexer(src), nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = new(token.Token)
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '?'
1: ':'
2: '<'
3: '>'
4: ';'
5: 'S'
6: 'E'
7: 'L'
8: 'E'
9: 'C'
10: 'T'
11: '*'
12: 'I'
13: 'N'
14: 'S'
15: 'E'
16: 'R'
17: 'T'
18: '{'
19: '}'
20: '.'
21: 'C'
22: 'O'
23: 'U'
24: 'N'
25: 'T'
26: 'F'
27: 'R'
28: 'O'
29: 'M'
30: 'W'
31: 'H'
32: 'E'
33: 'R'
34: 'E'
35: '|'
36: '/'
37: 'a'
38: '('
39: ')'
40: '?'
41: '+'
42: 'U'
43: 'N'
44: 'I'
45: 'O'
46: 'N'
47: '"'
48: '_'
49: '-'
50: '_'
51: '\'
52: '-'
53: '#'
54: '%'
55: '$'
56: '@'
57: '_'
58: '-'
59: ' '
60: ':'
61: '"'
62: '"'
63: '\t'
64: '\n'
65: '\r'
66: ' '
67: 'A'-'Z'
68: 'a'-'z'
69: '0'-'9'
70: .
*/
