// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 34: // ['"','"']
			return 2
		case r == 40: // ['(','(']
			return 3
		case r == 41: // [')',')']
			return 4
		case r == 42: // ['*','*']
			return 5
		case r == 43: // ['+','+']
			return 6
		case r == 45: // ['-','-']
			return 7
		case r == 46: // ['.','.']
			return 8
		case r == 47: // ['/','/']
			return 9
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 59: // [';',';']
			return 11
		case r == 60: // ['<','<']
			return 12
		case r == 63: // ['?','?']
			return 13
		case r == 65: // ['A','A']
			return 14
		case r == 66: // ['B','B']
			return 15
		case r == 67: // ['C','C']
			return 16
		case 68 <= r && r <= 69: // ['D','E']
			return 17
		case r == 70: // ['F','F']
			return 18
		case 71 <= r && r <= 72: // ['G','H']
			return 17
		case r == 73: // ['I','I']
			return 19
		case 74 <= r && r <= 82: // ['J','R']
			return 17
		case r == 83: // ['S','S']
			return 20
		case r == 84: // ['T','T']
			return 17
		case r == 85: // ['U','U']
			return 21
		case r == 86: // ['V','V']
			return 17
		case r == 87: // ['W','W']
			return 22
		case 88 <= r && r <= 90: // ['X','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case r == 97: // ['a','a']
			return 23
		case 98 <= r && r <= 122: // ['b','z']
			return 24
		case r == 123: // ['{','{']
			return 25
		case r == 124: // ['|','|']
			return 26
		case r == 125: // ['}','}']
			return 27
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 28
		default:
			return 2
		}
	},
	// S3
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S4
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 90: // ['A','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 90: // ['A','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		case r == 62: // ['>','>']
			return 30
		default:
			return 12
		}
	},
	// S13
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 31
		case 48 <= r && r <= 57: // ['0','9']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 33
		case r == 95: // ['_','_']
			return 31
		case 97 <= r && r <= 122: // ['a','z']
			return 34
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 69: // ['A','E']
			return 17
		case r == 70: // ['F','F']
			return 35
		case 71 <= r && r <= 83: // ['G','S']
			return 17
		case r == 84: // ['T','T']
			return 36
		case 85 <= r && r <= 90: // ['U','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 68: // ['A','D']
			return 17
		case r == 69: // ['E','E']
			return 37
		case 70 <= r && r <= 90: // ['F','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 78: // ['A','N']
			return 17
		case r == 79: // ['O','O']
			return 38
		case 80 <= r && r <= 90: // ['P','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 90: // ['A','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 81: // ['A','Q']
			return 17
		case r == 82: // ['R','R']
			return 39
		case 83 <= r && r <= 90: // ['S','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 77: // ['A','M']
			return 17
		case r == 78: // ['N','N']
			return 40
		case 79 <= r && r <= 90: // ['O','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 68: // ['A','D']
			return 17
		case r == 69: // ['E','E']
			return 41
		case 70 <= r && r <= 90: // ['F','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S21
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 77: // ['A','M']
			return 17
		case r == 78: // ['N','N']
			return 42
		case 79 <= r && r <= 90: // ['O','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S22
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 71: // ['A','G']
			return 17
		case r == 72: // ['H','H']
			return 43
		case 73 <= r && r <= 90: // ['I','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S23
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 90: // ['A','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S24
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 90: // ['A','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S25
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S26
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S27
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S28
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S29
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 44
		case 48 <= r && r <= 57: // ['0','9']
			return 45
		case 65 <= r && r <= 90: // ['A','Z']
			return 46
		case r == 95: // ['_','_']
			return 44
		case 97 <= r && r <= 122: // ['a','z']
			return 47
		}
		return NoState
	},
	// S30
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S31
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 31
		case 48 <= r && r <= 57: // ['0','9']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 33
		case r == 95: // ['_','_']
			return 31
		case 97 <= r && r <= 122: // ['a','z']
			return 34
		}
		return NoState
	},
	// S32
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 31
		case 48 <= r && r <= 57: // ['0','9']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 33
		case r == 95: // ['_','_']
			return 31
		case 97 <= r && r <= 122: // ['a','z']
			return 34
		}
		return NoState
	},
	// S33
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 31
		case 48 <= r && r <= 57: // ['0','9']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 33
		case r == 95: // ['_','_']
			return 31
		case 97 <= r && r <= 122: // ['a','z']
			return 34
		}
		return NoState
	},
	// S34
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 31
		case 48 <= r && r <= 57: // ['0','9']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 33
		case r == 95: // ['_','_']
			return 31
		case 97 <= r && r <= 122: // ['a','z']
			return 34
		}
		return NoState
	},
	// S35
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 83: // ['A','S']
			return 17
		case r == 84: // ['T','T']
			return 48
		case 85 <= r && r <= 90: // ['U','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S36
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 90: // ['A','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S37
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 69: // ['A','E']
			return 17
		case r == 70: // ['F','F']
			return 49
		case 71 <= r && r <= 90: // ['G','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S38
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 84: // ['A','T']
			return 17
		case r == 85: // ['U','U']
			return 50
		case 86 <= r && r <= 90: // ['V','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S39
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 78: // ['A','N']
			return 17
		case r == 79: // ['O','O']
			return 51
		case 80 <= r && r <= 90: // ['P','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S40
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 82: // ['A','R']
			return 17
		case r == 83: // ['S','S']
			return 52
		case 84 <= r && r <= 90: // ['T','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S41
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 75: // ['A','K']
			return 17
		case r == 76: // ['L','L']
			return 53
		case 77 <= r && r <= 90: // ['M','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S42
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 72: // ['A','H']
			return 17
		case r == 73: // ['I','I']
			return 54
		case 74 <= r && r <= 90: // ['J','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S43
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 68: // ['A','D']
			return 17
		case r == 69: // ['E','E']
			return 55
		case 70 <= r && r <= 90: // ['F','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S44
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 44
		case 48 <= r && r <= 57: // ['0','9']
			return 45
		case 65 <= r && r <= 90: // ['A','Z']
			return 46
		case r == 95: // ['_','_']
			return 44
		case 97 <= r && r <= 122: // ['a','z']
			return 47
		}
		return NoState
	},
	// S45
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 44
		case 48 <= r && r <= 57: // ['0','9']
			return 45
		case 65 <= r && r <= 90: // ['A','Z']
			return 46
		case r == 95: // ['_','_']
			return 44
		case 97 <= r && r <= 122: // ['a','z']
			return 47
		}
		return NoState
	},
	// S46
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 44
		case 48 <= r && r <= 57: // ['0','9']
			return 45
		case 65 <= r && r <= 90: // ['A','Z']
			return 46
		case r == 95: // ['_','_']
			return 44
		case 97 <= r && r <= 122: // ['a','z']
			return 47
		}
		return NoState
	},
	// S47
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 44
		case 48 <= r && r <= 57: // ['0','9']
			return 45
		case 65 <= r && r <= 90: // ['A','Z']
			return 46
		case r == 95: // ['_','_']
			return 44
		case 97 <= r && r <= 122: // ['a','z']
			return 47
		}
		return NoState
	},
	// S48
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 68: // ['A','D']
			return 17
		case r == 69: // ['E','E']
			return 56
		case 70 <= r && r <= 90: // ['F','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S49
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 78: // ['A','N']
			return 17
		case r == 79: // ['O','O']
			return 57
		case 80 <= r && r <= 90: // ['P','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S50
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 77: // ['A','M']
			return 17
		case r == 78: // ['N','N']
			return 58
		case 79 <= r && r <= 90: // ['O','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S51
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 76: // ['A','L']
			return 17
		case r == 77: // ['M','M']
			return 59
		case 78 <= r && r <= 90: // ['N','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S52
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 68: // ['A','D']
			return 17
		case r == 69: // ['E','E']
			return 60
		case 70 <= r && r <= 90: // ['F','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S53
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 68: // ['A','D']
			return 17
		case r == 69: // ['E','E']
			return 61
		case 70 <= r && r <= 90: // ['F','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S54
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 78: // ['A','N']
			return 17
		case r == 79: // ['O','O']
			return 62
		case 80 <= r && r <= 90: // ['P','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S55
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 81: // ['A','Q']
			return 17
		case r == 82: // ['R','R']
			return 63
		case 83 <= r && r <= 90: // ['S','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S56
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 81: // ['A','Q']
			return 17
		case r == 82: // ['R','R']
			return 64
		case 83 <= r && r <= 90: // ['S','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S57
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 81: // ['A','Q']
			return 17
		case r == 82: // ['R','R']
			return 65
		case 83 <= r && r <= 90: // ['S','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S58
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 83: // ['A','S']
			return 17
		case r == 84: // ['T','T']
			return 66
		case 85 <= r && r <= 90: // ['U','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S59
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 90: // ['A','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S60
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 81: // ['A','Q']
			return 17
		case r == 82: // ['R','R']
			return 67
		case 83 <= r && r <= 90: // ['S','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S61
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 66: // ['A','B']
			return 17
		case r == 67: // ['C','C']
			return 68
		case 68 <= r && r <= 90: // ['D','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S62
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 77: // ['A','M']
			return 17
		case r == 78: // ['N','N']
			return 69
		case 79 <= r && r <= 90: // ['O','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S63
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 68: // ['A','D']
			return 17
		case r == 69: // ['E','E']
			return 70
		case 70 <= r && r <= 90: // ['F','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S64
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 90: // ['A','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S65
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 68: // ['A','D']
			return 17
		case r == 69: // ['E','E']
			return 71
		case 70 <= r && r <= 90: // ['F','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S66
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 90: // ['A','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S67
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 83: // ['A','S']
			return 17
		case r == 84: // ['T','T']
			return 72
		case 85 <= r && r <= 90: // ['U','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S68
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 83: // ['A','S']
			return 17
		case r == 84: // ['T','T']
			return 73
		case 85 <= r && r <= 90: // ['U','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S69
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 90: // ['A','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S70
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 90: // ['A','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S71
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 90: // ['A','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S72
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 90: // ['A','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S73
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 7
		case 48 <= r && r <= 57: // ['0','9']
			return 10
		case r == 58: // [':',':']
			return 29
		case 65 <= r && r <= 90: // ['A','Z']
			return 17
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
}
