/* 
 * Swagger HodDB
 *
 * This is a description of the HodDB API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Body struct {

	Query string `json:"query,omitempty"`
}
