/* 
 * Swagger HodDB
 *
 * This is a description of the HodDB API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// key-value pairs of variable names and their values
type Triple struct {
}
