/* 
 * Swagger HodDB
 *
 * This is a description of the HodDB API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type TripleResponse struct {

	// Query results
	Rows []interface{} `json:"Rows,omitempty"`

	// Number of rows returned
	Count int64 `json:"Count,omitempty"`

	// Nanoseconds elapsed during evaluation
	Elapsed int64 `json:"Elapsed,omitempty"`
}
